---
- name: update source
  git:
    repo: 'https://github.com/densuke-st/park.git'
    dest: /home/0j02050/park
  become_user: 0j02050  
  register: src
- name: install modules
  shell: |
     source ~/venv/bin/activate
     pip3 install -r requirements.txt
  args:
    chdir: /home/0j02050/park
  become_user: 0j02050
  when: src is changed
- name: append venv to .bashrc
  lineinfile:
    path: /home/0j02050/.bashrc
    line: "VIRTUAL_ENV_DISABLE_PROMPT=1; source ~/venv/bin/activate"
    

